### ISSUE TITLE
Exception: None of the configured nodes are available

### ISSUE THREAD

**Issue by zores** [WedjaaOpen/ElasticJasperSite#3]
Hi,

First of all, thanks for this great plugin!

Now to the boring part, I have some issues with Jaspersoft Studio 6.2.0 and the ElasticJasperSite plugin when trying to connect to the ES (version 2.1) server. The exception I get is:

```
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
    at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:278)
    at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:197)
    at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106)
    at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:334)
    at org.elasticsearch.client.transport.TransportClient.search(TransportClient.java:424)
    at org.elasticsearch.action.search.SearchRequestBuilder.doExecute(SearchRequestBuilder.java:1116)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
    at net.wedjaa.elasticparser.ESSearch.executeSearch(ESSearch.java:492)
    at net.wedjaa.elasticparser.ESSearch.executeSearch(ESSearch.java:504)
    at net.wedjaa.elasticparser.ESSearch.runQuery(ESSearch.java:541)
    at net.wedjaa.elasticparser.ESSearch.runQuery(ESSearch.java:554)
    at net.wedjaa.elasticparser.ESSearch.getFields(ESSearch.java:607)
    at net.wedjaa.elasticparser.ESSearch.getFields(ESSearch.java:617)
    at net.wedjaa.elasticparser.ESSearch.test(ESSearch.java:624)
    at net.wedjaa.jasper.elasticsearch.adapter.ESAdapterService.test(ESAdapterService.java:114)
    at com.jaspersoft.studio.data.wizard.AbstractDataAdapterWizard$3.runOperations(AbstractDataAdapterWizard.java:162)
    at com.jaspersoft.studio.utils.jobs.CheckedRunnableWithProgress$1.run(CheckedRunnableWithProgress.java:59)
    at java.lang.Thread.run(Thread.java:745)
```

Any theories to why this is, and preferably, how do I solve it?

Thanks in advance!

**Comment by Wedjaa** [comment]
Hi Zores,

  I will look into it - I haven't tested the current plugin with ES 2.1. Will test and let you know what I find out.

  Fabio

**Comment by Wedjaa** [comment]
The latest release is compatible with ES up to 2.2 - give it a spin and let me know if the issue persist. Make sure you are using port 9300 to connect to ES and that the port is reachable by Jasper Studio.

**Comment by zores** [comment]
Sorry for late reply!

Works like a charm! Thank you so much!
